SYSTEM_NAME="apple2"
SYSTEM_FULLNAME="Apple II/II+/IIe/Enhanced IIe"
SYSTEM_MANUFACTURER="Apple"
SYSTEM_RELEASE="1977"
SYSTEM_HARDWARE="computer"
SYSTEM_PATH="/storage/roms/apple2"
SYSTEM_EXTENSION=".d13 .dsk .po .woz .hdv .zip .7z"
SYSTEM_COMMAND="/usr/bin/runemu.sh %ROM% -P%SYSTEM% --core=%CORE% --emulator=%EMULATOR% --controllers=\"%CONTROLLERSCONFIG%\""
SYSTEM_PLATFORM="apple2"
SYSTEM_THEME="apple2"
SYSTEM_WIKI_PATH="apple2"
